version: 0.2

env:
  variables:
    IMAGE_NAME: "my-image"  # Default (override in CodeBuild)
  parameter-store:
    AWS_REGION: "/codebuild/aws-region"
    ACCOUNT_ID: "/codebuild/account-id"
    IMAGE_REPO: "/codebuild/image-repo"
    IMAGE_TAG: "/codebuild/image-tag"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO:$IMAGE_TAG .
      - docker tag $IMAGE_REPO:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO:$IMAGE_TAG
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
